// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(FormularioContext))]
    [Migration("20210209155051_FormularioDosNuevos")]
    partial class FormularioDosNuevos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.FormularioDesperfectoMovil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desperfecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EscInsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<short>("MovCod")
                        .HasColumnType("smallint");

                    b.Property<int>("MovilKilometraje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormularioDesperfectoMovil");
                });

            modelBuilder.Entity("Models.FormularioDiarioMovil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Combustible")
                        .HasColumnType("bit");

                    b.Property<string>("EscInsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LucesDelanterasCortasDerecha")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasCortasIzquierda")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasLargasDerecha")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasLargasIzquierda")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasSenialeroDerecho")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasSenialeroIzquierdo")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasFreno")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasPosicionDerecha")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasPosicionIzquierda")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasReversa")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasSenialeroDerecho")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasSenialeroIzquierdo")
                        .HasColumnType("bit");

                    b.Property<short>("MovCod")
                        .HasColumnType("smallint");

                    b.Property<int>("MovilKilometraje")
                        .HasColumnType("int");

                    b.Property<bool>("NivelAceite")
                        .HasColumnType("bit");

                    b.Property<bool>("NivelAgua")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoAuxiliar")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoBaliza")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoConos")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoExtintor")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormularioDiarioMovil");
                });
#pragma warning restore 612, 618
        }
    }
}
