// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(FormularioContext))]
    partial class FormularioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.FormularioDesperfectoMovil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desperfecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EscInsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<short>("MovCod")
                        .HasColumnType("smallint");

                    b.Property<int>("MovilKilometraje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormularioDesperfectoMovil");
                });

            modelBuilder.Entity("Models.FormularioDiarioMovil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Combustible")
                        .HasColumnType("bit");

                    b.Property<string>("EscInsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LucesDelanterasCortasDerecha")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasCortasIzquierda")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasLargasDerecha")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasLargasIzquierda")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasSenialeroDerecho")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesDelanterasSenialeroIzquierdo")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasFreno")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasPosicionDerecha")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasPosicionIzquierda")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasReversa")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasSenialeroDerecho")
                        .HasColumnType("bit");

                    b.Property<bool>("LucesTracerasSenialeroIzquierdo")
                        .HasColumnType("bit");

                    b.Property<short>("MovCod")
                        .HasColumnType("smallint");

                    b.Property<int>("MovilKilometraje")
                        .HasColumnType("int");

                    b.Property<bool>("NivelAceite")
                        .HasColumnType("bit");

                    b.Property<bool>("NivelAgua")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoAuxiliar")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoBaliza")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoConos")
                        .HasColumnType("bit");

                    b.Property<bool>("ObjetoExtintor")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormularioDiarioMovil");
                });

            modelBuilder.Entity("Models.FormularioEvaluacionAlumno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AceptaIndicacionesInstructor")
                        .HasColumnType("int");

                    b.Property<string>("AlumnoNombreApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CirculaManteniendoDerecha")
                        .HasColumnType("int");

                    b.Property<int>("DominaAdministracionCambios")
                        .HasColumnType("int");

                    b.Property<int>("DominaUsoEspejos")
                        .HasColumnType("int");

                    b.Property<int>("DominaUsoPedales")
                        .HasColumnType("int");

                    b.Property<int>("DominaVehiculoEnRepecho")
                        .HasColumnType("int");

                    b.Property<string>("EscInsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estacionamient45GradosDerecho")
                        .HasColumnType("int");

                    b.Property<int>("Estacionamient45GradosIzquierdo")
                        .HasColumnType("int");

                    b.Property<int>("EstacionamientoLateralDerecho")
                        .HasColumnType("int");

                    b.Property<int>("EstacionamientoLateralIzquierdo")
                        .HasColumnType("int");

                    b.Property<int>("EvaluaEnfrentaAdecuadamenteDificultades")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrenaConSuficienteAnticipacion")
                        .HasColumnType("int");

                    b.Property<int>("GiroIngresaCorrectamenteNuevaVia")
                        .HasColumnType("int");

                    b.Property<int>("GiroSenializaCorrectamente")
                        .HasColumnType("int");

                    b.Property<int>("GiroUbicacionCorrectamente")
                        .HasColumnType("int");

                    b.Property<int>("GiroVelocidadCorrecta")
                        .HasColumnType("int");

                    b.Property<int>("MantieneDistanciaSeguridad")
                        .HasColumnType("int");

                    b.Property<int>("MantieneVelocidadAdecuada")
                        .HasColumnType("int");

                    b.Property<int>("MarchaAtras")
                        .HasColumnType("int");

                    b.Property<short>("NumeroClase")
                        .HasColumnType("smallint");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgresoEncendidoEnNeutro")
                        .HasColumnType("int");

                    b.Property<int>("ProgresoEnciendeVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("ProgresoMarchaVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("ReconoceSentidosCirculacion")
                        .HasColumnType("int");

                    b.Property<int>("RespetaOtrosUsuariosDeLaVia")
                        .HasColumnType("int");

                    b.Property<int>("RespetaSendasPeatonales")
                        .HasColumnType("int");

                    b.Property<int>("RespetaTodasSenialesTransito")
                        .HasColumnType("int");

                    b.Property<int>("SaleConduciendoACU")
                        .HasColumnType("int");

                    b.Property<int>("SeguridadCinturon")
                        .HasColumnType("int");

                    b.Property<int>("SeguridadRegulaButacaApoyaCabezas")
                        .HasColumnType("int");

                    b.Property<int>("SeguridadRegulaEspejos")
                        .HasColumnType("int");

                    b.Property<int>("SenializaCorrectamenteCambioCarril")
                        .HasColumnType("int");

                    b.Property<int>("SenializaManiobrasARealizar")
                        .HasColumnType("int");

                    b.Property<int>("Slalom")
                        .HasColumnType("int");

                    b.Property<int>("TieneBuenaTecnicaBrazos")
                        .HasColumnType("int");

                    b.Property<int>("ToleranciaStressTransito")
                        .HasColumnType("int");

                    b.Property<int>("VuelveConduciendoACU")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormularioEvaluacionAlumno");
                });

            modelBuilder.Entity("Models.FormularioResultadoExamenPractico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlumnoNombreApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleMotivoPerdida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsAlumnoOtroInstructor")
                        .HasColumnType("bit");

                    b.Property<string>("EscInsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorAlumnoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotivoReprobacionCalle")
                        .HasColumnType("int");

                    b.Property<int?>("MotivoReprobacionPista")
                        .HasColumnType("int");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormularioResultadoExamenPractico");
                });
#pragma warning restore 612, 618
        }
    }
}
